### ISSUE TITLE
Broken for 4.3.4

### ISSUE THREAD

**Issue by jwh1981** [mangostools/MangosWoWRegeneration#1]
Unfortunately, this tool no longer appears to work for 4.3.4. The following happens:

Which version of World of Warcraft you want to restore :

[01] World of Warcraft 4.3.4 (15595)
[02] World of Warcraft 5.1.0 (16357)
[03] World of Warcraft 5.1.1 (16685)
[04] World of Warcraft 5.4.8 (18414)

Select version :
1
Unable to retrieve Manifest file
The remote server returned an error: (404) Not Found.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WoWRegeneration.UI.UserInputs.SelectLocale(ManifestFile manifest)
   at WoWRegeneration.WoWRegeneration.EntryPointNewSession()
   at WoWRegeneration.Program.Main()

**Comment by billy1arm** [comment]
@jwh1981 - I can confirm that blizz have either now shut down this server or changed the address.

Should anyone know of an alternate address, please let me know.

**Comment by jwh1981** [comment]
@billy1arm I was thinking that as well. I imagine Blizzard only allows for patches from clients that are 5.x or higher and killed the old url's. It makes sense but sucks 👎

**Comment by CraftedRO** [comment]
#2
